# -*- coding: utf-8 -*-
"""Shravani_DIP_CCA3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WYcYo2W1RG3hyMrQSTpXKTbEAjHtdpZx
"""

#DISCRETE WAVELET TRANSFORM (DWT)

import cv2
import pywt
import matplotlib.pyplot as plt

# Load image (grayscale)
img = cv2.imread(cv2.samples.findFile('/content/woman.tiff'), 0)

# Perform 2D DWT
coeffs2 = pywt.dwt2(img, 'haar')
LL, (LH, HL, HH) = coeffs2

# Display results
titles = ['Approximation (LL)', 'Horizontal detail (LH)', 'Vertical detail (HL)', 'Diagonal detail (HH)']
images = [LL, LH, HL, HH]

plt.figure(figsize=(8,8))
for i in range(4):
    plt.subplot(2,2,i+1)
    plt.imshow(images[i], cmap='gray')
    plt.title(titles[i])
    plt.axis('off')
plt.tight_layout()
plt.show()